# Generated by Django 5.1.7 on 2025-06-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0002_remove_player_matches_played_remove_player_runs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='player_images/'),
        ),
    ]
